### ISSUE TITLE
Refactor the Action class and all its subtypes

### ISSUE THREAD

**Issue by luisrozo** [avleze/TextAdventures#12]
The abstract class **Action** has an only parameter: __description__ (it is a String). But maybe we should refactor the class, adding a _PlayerCharacter_ as a instance variable in order to send it through the sub-classes as a formal parameter. This is because of the fact that **MovementAction** doesn't have to receive an **Enemy**, which is only required by the **BattleAction** subtype. So, the new design would be something like this:

![Classes](https://i.imgsafe.org/6d82bbd33b.png)

**Comment by avleze** [comment]
Ok, we will design it according to this diagram instead of the older one.

Thanks.
