### ISSUE TITLE
Changes in Player , WeaponItem and RecoveryItem class

### ISSUE THREAD

**Issue by juanrodicio** [avleze/TextAdventures#15]
In order to save the current game on the DB i need these methods.

```java
class Player{
    public int getBaseDamage();
}

class WeaponItem{
    public int getDamage();
}

class RecoveryItem{
    public int getPointsToHealth();
}
```

Thank you! :)

**Comment by juanrodicio** [comment]
In WeaponItem, ArmorItem and RecoveryItem class is needed to set the ID.

**Comment by manuelrdsg** [comment]
Added getBaseDamage() method to Player. The remaining methods were already implemented with the name "use()". Also in classes WeaponItem, ArmorItem, RecoveryItem a call to super constructor has been added.
