### ISSUE TITLE
BattleAction and subclasses are not clear at all

### ISSUE THREAD

**Issue by luisrozo** [avleze/TextAdventures#16]
During the last class, @juanrodicio, @manuelrdsg, me and the teacher Pablo talked about a new battle system. 

In addition to other points of the UML diagram, we focused on the abstract class Action. Previously, it was inherited by MovementAction, BattleAction and UseItemAction. However, now it is inherited only by MovementAction and BattleAction, which is now an abstract class too, which is inherited by three new classes: Attack, Heal and Run.

How would an updated UML diagram look like with this changes? I think everything is quite confusing... I would like to discuss about which methods have every class to implement, and every single private attribute.

**Comment by avleze** [comment]
The main topic is what was the reason why you inherited new classes from BattleAction. I would update the UML classes diagram if I know what I have to change.
