### ISSUE TITLE
Differences between "set" methods of Map and Room classes

### ISSUE THREAD

**Issue by luisrozo** [avleze/TextAdventures#3]
Within both classes, there is a "set" method for _rooms_ (Map) and _message_ (Room).

setRooms receives an Array[][] of Room, and the type of instance variable **_rooms_** is Array[][] of Room.

However, setMessage receives a String, whistl the type of instance variable **_message_** is Message. 

Wouldn't be better that setMessage receives a Message instead of a String?

**Comment by avleze** [comment]
Yes, we have to update the UML diagram, so I am going to leave this issue opened.

Thank you Luis.
